version: '3.8'

services:
  module1:
    build:
      context: ./sklon-web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rc1a-73lxg215z7ep4vxf.mdb.yandexcloud.net:6432/db1
      - SPRING_DATASOURCE_USERNAME=postgres1
      - SPRING_DATASOURCE_PASSWORD=postgres1