spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://rc1b-7xfmxrgl17kcsd0p.mdb.yandexcloud.net:6432/db1
    username: postgres1
    password: postgres1
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db.changelog/app-changelog.xml
    default-schema: sklon_liquibase

