spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://rc1d-c75tce3acct1by6g.mdb.yandexcloud.net:3306/sklon_db
    username: evgen1234
    password: evgen1234
    driver-class-name: com.mysql.jdbc.Driver

  liquibase:
    change-log: classpath:db.changelog/app-changelog.xml
