name: CD Deploy

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: sklon-web

      - name: Deploy to VPS
        env:
          YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          # Установка Yandex Cloud CLI
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH=$PATH:$HOME/yandex-cloud/bin

          echo "$YC_SA_JSON_CREDENTIALS" > yc-sa-key.json
          yc config set service-account-key yc-sa-key.json

          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key

          # Добавление известного хоста
          mkdir -p ~/.ssh
          ssh-keyscan -H 51.250.101.151 >> ~/.ssh/known_hosts

          # Копирование и запуск приложения
          scp -i ssh_key ./sklon-web-0.0.1-SNAPSHOT.jar eabaev@51.250.101.151:/home/eabaev/myapp/
          ssh -i ssh_key eabaev@51.250.101.151 'sudo java -jar /home/eabaev/myapp/sklon-web-0.0.1-SNAPSHOT.jar &'
