name: CI/CD Pipeline

on:
  push:
    branches:
      - 'master'
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: sklon-web/target/sklon-web-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Deploy to VPS
        env:
          YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          # Установка Yandex Cloud CLI
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH=$PATH:$HOME/yandex-cloud/bin
          
          echo "$YC_SA_JSON_CREDENTIALS" > yc-sa-key.json
          yc config set service-account-key yc-sa-key.json
          
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          
          # Добавление известного хоста
          mkdir -p ~/.ssh
          ssh-keyscan -H 51.250.101.151 >> ~/.ssh/known_hosts

          # Остановка и удаление старого приложения (если оно запущено)
          ssh -i ssh_key eabaev@51.250.101.151 << 'EOF'
            sudo -i
            # Проверяем, есть ли процессы на порту 8080
            PIDS=$(sudo lsof -t -iTCP:8080 -sTCP:LISTEN)
            if [ -n "$PIDS" ]; then
              echo "Stopping the old application..."
              kill $PIDS || true  # Остановка процесса на порту 8080, если он есть
            else
              echo "No application running on port 8080."
            fi
            
            echo "Removing old application..."
            sudo rm -rf /home/eabaev/myapp/sklon-web-0.0.1-SNAPSHOT.jar || true  # Удаление старого JAR файла
          EOF

          # Копирование нового приложения и запуск его в фоновом режиме
          scp -i ssh_key ./sklon-web-0.0.1-SNAPSHOT.jar eabaev@51.250.101.151:/home/eabaev/myapp/
          ssh -i ssh_key eabaev@51.250.101.151 'sudo java -jar /home/eabaev/myapp/sklon-web-0.0.1-SNAPSHOT.jar &'

          sleep 10  # Ждем некоторое время, чтобы приложение успело запуститься


          for i in {1..2}; do  # Проверяем 10 раз с интервалом в 5 секунд
            if curl --silent --fail http://51.250.101.151:8080/objects; then 
              echo "Application is up and running!"
              exit 0  # Успех, завершаем выполнение скрипта с кодом 0
            fi
            echo "Waiting for application to start..."
            sleep 5  
          done
          echo "Application did not start successfully." 
          exit 1  # Если приложение не запустилось, завершаем с ошибкой
