name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to VPS
        env:
          YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          # Установка Yandex Cloud CLI
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH=$PATH:$HOME/yandex-cloud/bin

          echo "$YC_SA_JSON_CREDENTIALS" > yc-sa-key.json
          yc config set service-account-key yc-sa-key.json

          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key

          # Добавление известного хоста
          mkdir -p ~/.ssh
          ssh-keyscan -H 51.250.101.151 >> ~/.ssh/known_hosts

          # Копирование и запуск приложения
          scp -i ssh_key ./sklon-web/target/sklon-web-0.0.1-SNAPSHOT.jar eabaev@51.250.101.151:/home/eabaev/myapp/
          ssh -i ssh_key eabaev@51.250.101.151 'sudo java -jar /home/eabaev/myapp/sklon-web-0.0.1-SNAPSHOT.jar &'
