name: CI/CD Pipeline

on:
  push:
    branches:
      - 'master'
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: sklon-web/target/sklon-web-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Deploy to VPS
        env:
          YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          # Установка Yandex Cloud CLI
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH=$PATH:$HOME/yandex-cloud/bin
          
          echo "$YC_SA_JSON_CREDENTIALS" > yc-sa-key.json
          yc config set service-account-key yc-sa-key.json
          
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          
          # Добавление известного хоста
          mkdir -p ~/.ssh
          ssh-keyscan -H 84.201.145.141 >> ~/.ssh/known_hosts

          # Копирование нового приложения на VPS
          scp -i ssh_key ./sklon-web-0.0.1-SNAPSHOT.jar paw@84.201.145.141:/home/paw/

          # Создание Dockerfile для приложения
          ssh -i ssh_key paw@84.201.145.141 << 'EOF'
            echo "FROM openjdk:11-jre-slim" > /home/paw/Dockerfile
            echo "COPY sklon-web-0.0.1-SNAPSHOT.jar /app.jar" >> /home/paw/Dockerfile
            echo "ENTRYPOINT [\"java\", \"-jar\", \"/app.jar\"]" >> /home/paw/Dockerfile
          
            # Создание и запуск Docker контейнера с приложением
            sudo docker build -t sklon-web /home/paw/
            sudo docker run -d --name sklon-web -p 8080:8080 sklon-web
          EOF

          sleep 10  # Ждем некоторое время, чтобы приложение успело запуститься

          # Проверка состояния приложения
          for i in {1..2}; do  # Проверяем 2 раза с интервалом в 5 секунд
            if curl --silent --fail http://84.201.145.141:8080/objects; then 
              echo "Application is up and running!"
              exit 0  # Успех, завершаем выполнение скрипта с кодом 0
            fi
            echo "Waiting for application to start..."
            sleep 5  
          done
          echo "Application did not start successfully." 
          exit 1  # Если приложение не запустилось, завершаем с ошибкой