name: CI/CD Pipeline

on:
  push:
    branches:
      - 'master'
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: sklon-web/target/sklon-web-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Deploy to VPS
        env:
          YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          # Установка Yandex Cloud CLI
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH=$PATH:$HOME/yandex-cloud/bin
          
          echo "$YC_SA_JSON_CREDENTIALS" > yc-sa-key.json
          yc config set service-account-key yc-sa-key.json
          
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          
          # Добавление известного хоста
          mkdir -p ~/.ssh
          ssh-keyscan -H 51.250.101.151 >> ~/.ssh/known_hosts
          
          # Удаление старого приложение
          ssh -i ssh_key eabaev@51.250.101.151 << 'EOF'
            if pgrep -f "sklon-web-0.0.1-SNAPSHOT.jar" > /dev/null; then
              echo "Stopping the old application..."
              kill $(lsof -ti tcp:8080) || true  # Остановка процесса на порту 8080, если он есть
            fi
          
            echo "Removing old application..."
            sudo rm -rf /home/eabaev/myapp/sklon-web-0.0.1-SNAPSHOT.jar || true  # Удаление старого JAR файла, если он есть
          EOF
          
          # Копирование и запуск приложения
          scp -i ssh_key ./sklon-web-0.0.1-SNAPSHOT.jar eabaev@51.250.101.151:/home/eabaev/myapp/
          ssh -i ssh_key eabaev@51.250.101.151 'sudo java -jar /home/eabaev/myapp/sklon-web-0.0.1-SNAPSHOT.jar &'
      - name: Wait for application to start
        run: |
          sleep 600  # Ждем некоторое время, чтобы приложение успело запуститься

      - name: Check application status
        run: |
          for i in {1..10}; do  # Проверяем 10 раз с интервалом в 5 секунд
            if curl --silent --fail http://51.250.101.151:8080/actuator/health; then 
              echo "Application is up and running!"
              exit 0  # Успех, завершаем выполнение скрипта с кодом 0
            fi
            echo "Waiting for application to start..."
            sleep 5  
          done
          echo "Application did not start successfully." 
          exit 1  # Если приложение не запустилось, завершаем с ошибкой
