  name: CI/CD Pipeline

  on:
    push:
      branches:
        - '*'

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn clean package

    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to Yandex Cloud
          env:
            YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
            
            # Установка Yandex Cloud CLI
            curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
            export PATH=$PATH:/home/runner/yandex-cloud/bin
            
            # Настройка Yandex Cloud CLI
            echo "$YC_SA_JSON_CREDENTIALS" > yc-sa-key.json
            yc config set service-account-key yc-sa-key.json
            
            # Настройка SSH
            echo "$SSH_PRIVATE_KEY" > ssh_key
            chmod 600 ssh_key
            
            # Копирование файла на сервер
            scp -i ssh_key -o StrictHostKeyChecking=no target/sklon-web-0.0.1-SNAPSHOT.jar ubuntu@51.250.100.141:/home/ubuntu/myapp/
            
            # Опционально: выполнение команд на удаленном сервере
            ssh -i ssh_key -o StrictHostKeyChecking=no deckhouse@51.250.100.141 "cd /home/ubuntu/myapp && java -jar sklon-web-0.0.1-SNAPSHOT.jar"
          shell: /usr/bin/bash -e {0}
