  name: CI/CD Pipeline

  on:
    push:
      branches:
        - '*'

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn clean package

    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to Yandex Cloud
          env:
            YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
            # Установка Yandex Cloud CLI
            curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
            export PATH=$PATH:/home/runner/yandex-cloud/bin

            echo "$YC_SA_JSON_CREDENTIALS" > yc-sa-key.json
            yc config set service-account-key yc-sa-key.json

            echo "$SSH_PRIVATE_KEY" > ssh_key
            chmod 600 ssh_key

            # Добавление известного хоста
            mkdir -p ~/.ssh
            ssh-keyscan -H 51.250.101.151 >> ~/.ssh/known_hosts

            # Отладочная информация
            ls -la ~/.ssh
            cat ~/.ssh/known_hosts

            # Попытка SSH-подключения с подробным выводом
            ssh -v -i ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkg+hK4NA9O25oPBXqn/ovnKw7ERzm+RcT5gZeZdl4sThhzXfZ/HPO5XW0M6ZMFLF+dnlDd5Ex8t6kOGrjgzXrwr8ADjtRxiDANy9B7YqFz+vPqMn0GaOHw3SDLFRoNwCq4DwQcyFTdpowEWr7tpDOTiTMTvYC0nZlVYH9lZ/P0jk6UnYPtT4IdrbOvGjuiGa1vcEnBgO9zpc1vb0aBANbWkloUMlRD0GHrwLeFv8x46Y7dGD0LMlN0vtqc8YpMsX18N7zTrRNFjnaQTIEH7agFXUCcouebo94K6Q2MuoeH+ceMmRaralyD5HqNSMkFtoC+a6MSDpkxOK2KQjlveKMnqPy+/uSADmTqXz3oRUsoqZ/CtqAYl9sMO584Yq/uWMDTgd0AbVOktdb47OV7CzQZoAfbo25VtRnxCI8YjuCmrLhhJ+8Ws+YkEgobz7QUK3eUrGobc1ZD2/6PfCYWu/Ip6P63xvHtolLopw4Cy33ulm6LqeYi2MdiFWdHCzP0tc= abaev@WIN-D8PHGDU4HHG eabaev@51.250.101.151 'echo "SSH connection successful"'

            # Копирование и запуск приложения
            scp -i ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkg+hK4NA9O25oPBXqn/ovnKw7ERzm+RcT5gZeZdl4sThhzXfZ/HPO5XW0M6ZMFLF+dnlDd5Ex8t6kOGrjgzXrwr8ADjtRxiDANy9B7YqFz+vPqMn0GaOHw3SDLFRoNwCq4DwQcyFTdpowEWr7tpDOTiTMTvYC0nZlVYH9lZ/P0jk6UnYPtT4IdrbOvGjuiGa1vcEnBgO9zpc1vb0aBANbWkloUMlRD0GHrwLeFv8x46Y7dGD0LMlN0vtqc8YpMsX18N7zTrRNFjnaQTIEH7agFXUCcouebo94K6Q2MuoeH+ceMmRaralyD5HqNSMkFtoC+a6MSDpkxOK2KQjlveKMnqPy+/uSADmTqXz3oRUsoqZ/CtqAYl9sMO584Yq/uWMDTgd0AbVOktdb47OV7CzQZoAfbo25VtRnxCI8YjuCmrLhhJ+8Ws+YkEgobz7QUK3eUrGobc1ZD2/6PfCYWu/Ip6P63xvHtolLopw4Cy33ulm6LqeYi2MdiFWdHCzP0tc= abaev@WIN-D8PHGDU4HHG target/sklon-web-0.0.1-SNAPSHOT.jar eabaev@51.250.101.151:/home/ubuntu/myapp/
            ssh -i ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkg+hK4NA9O25oPBXqn/ovnKw7ERzm+RcT5gZeZdl4sThhzXfZ/HPO5XW0M6ZMFLF+dnlDd5Ex8t6kOGrjgzXrwr8ADjtRxiDANy9B7YqFz+vPqMn0GaOHw3SDLFRoNwCq4DwQcyFTdpowEWr7tpDOTiTMTvYC0nZlVYH9lZ/P0jk6UnYPtT4IdrbOvGjuiGa1vcEnBgO9zpc1vb0aBANbWkloUMlRD0GHrwLeFv8x46Y7dGD0LMlN0vtqc8YpMsX18N7zTrRNFjnaQTIEH7agFXUCcouebo94K6Q2MuoeH+ceMmRaralyD5HqNSMkFtoC+a6MSDpkxOK2KQjlveKMnqPy+/uSADmTqXz3oRUsoqZ/CtqAYl9sMO584Yq/uWMDTgd0AbVOktdb47OV7CzQZoAfbo25VtRnxCI8YjuCmrLhhJ+8Ws+YkEgobz7QUK3eUrGobc1ZD2/6PfCYWu/Ip6P63xvHtolLopw4Cy33ulm6LqeYi2MdiFWdHCzP0tc= abaev@WIN-D8PHGDU4HHG eabaev@51.250.101.151 'sudo java -jar /home/ubuntu/myapp/sklon-web-0.0.1-SNAPSHOT.jar &'
